export {default as Accounts} from './Admin-Accounts/Accounts'
export {default as ChapterInstall} from './ChapterInstall/ChapterInstall'
export {default as Chapters} from './Chapters/Chapters'
export {default as ChapterUpload} from './ChapterUpload/ChapterUpload'
export {default as Contact} from './Contact/Contact'
export {default as Course} from './Courses/Course'
export {default as Exam} from './Exam/Exam'
export {default as FileUpload} from './FileUpload/FileUpload'
export {default as Home} from './Home/Home'
export {default as Quiz} from './Quiz/Quiz'
export {default as SignIn} from './SignIn/SignIn'
export {default as AdminCourses} from "./Admin-Courses/AdminCourses";
export {default as DashboardPage} from "./DashboardPage/DashboardPage";
export {default as Profile} from "./Profile/Profile";
export {default as Assignments} from './Assignments/Assignments';
export {default as UploadAssignment} from './UploadAssignment/UploadAssignment';